export const ELEMENTS = {
   pageElementIdentifier: "div.login-form > h2 > b",
   maleGenderRadio: "input#id_gender1",
   passwordInput: 'input[data-qa="password"]',
   birthDaySelect: 'select[data-qa="days"]',
   birthMonthSelect: 'select[data-qa="months"]',
   birthYearSelect: 'select[data-qa="years"]',
   countrySelect: 'select[data-qa="country"]',
   newsletterCheckbox: "input#newsletter",
   offersCheckbox: "input#optin",
   firstNameInput: 'input[data-qa="first_name"]',
   lastNameInput: 'input[data-qa="last_name"]',
   companyInput: 'input[data-qa="company"]',
   addressInput: 'input[data-qa="address"]',
   secondAddressInput: 'input[data-qa="address2"]',
   stateInput: 'input[data-qa="state"]',
   cityInput: 'input[data-qa="city"]',
   zipCodeInput: 'input[data-qa="zipcode"]',
   mobileNumberInput: 'input[data-qa="mobile_number"]',
   createAccountButton: 'button[data-qa="create-account"]',
};
